---
title: "basic-freq-table"
format: html
editor: visual
---

# load-packages
```{r}
library(compareGroups)
library(tidyverse)
```

# prepare the data
```{r}
df_ana <- df_incu_india_raw %>% 
  filter(A2 != "Transgender")
```


# Unweighted frequencies by sex for all sections

## Section A
```{r}
tab1 <- compareGroups(A2 ~ A4 + A5 + A6 + A6_Other + A7 + A8 + A9 + 
                        A10 + A11 + A12 + A13 + A14 + A15 + A16 + A17, 
                      data = df_ana)
tab1_out <- createTable(tab1, digits.p = 2, digits = 2)
export2xls(tab1_out, "./outputs/sex-disaggregated-freq-sec-A.xlsx")
```

## Section B
```{r}
tab2 <- compareGroups(A2 ~ B1 + B3 + B4 + B4X + B5 + B6 + B7 + B8 + B9 + B10 + 
                        B11 + B12 + B12X + B12M + B12XM + B14a + B14b + B14c + B14d , 
                      data = df_ana)
tab2_out <- createTable(tab2, digits.p = 2, digits = 2)
export2xls(tab2_out, "./outputs/sex-disaggregated-freq-sec-B.xlsx")
```

## Section C
```{r}
tab3 <- compareGroups(A2 ~ C1 + C2 + C3 + C4 + C5 + C6 + C7 + C8 + C9 + C10 + 
                        C11 + C12 + C13 + C13X + C14 + C15 + C16_1 + C16_2 + 
                        C17 + C18 + C19 + C20 + C21 + C22 + C23a + C23b + 
                        C23c + C23d + C23e + C23f + C23g + C23h + C23i + C23j + 
                        C23l + C24 + C25 + C26 + C27 + C28 + C29 + C30a + C30b + 
                        C30c + C30d + C31 + C32 + C33a + C33b + C33c + C33d + 
                        C33e + C33f + C33g + C33h + C33i + C33j + C33k + C33l , 
                      data = df_ana)
(tab3_out <- createTable(tab3, digits.p = 2, digits = 2))
export2xls(tab3_out, "./outputs/sex-disaggregated-freq-sec-C.xlsx")
```

## Section D
```{r}
tab4 <- compareGroups(A2 ~ D1 + D4 + D6 + D7 + D6X + D7X + D8 + D9a + D9b + 
                        D9c + D9d + D9e + D10 + D10a + D10b + D10c + D10d + 
                        D10e + D10Xa + D10Xb + D10Xc + D10Xd + D10Xe + D11a + 
                        D11b + D11c + D11d + D11e + D12 + D13 , 
                      data = df_ana)
tab4_out <- createTable(tab4, digits.p = 2, digits = 2)
export2xls(tab4_out, "./outputs/sex-disaggregated-freq-sec-D.xlsx")
```

## Section E
```{r}
tab5 <- compareGroups(A2 ~ E1 + E3 + E4 + E5a + E5b + E5c + E5d + E6 + E7 + E8 + 
                        E10 + E11 + E12 + E13 + E14 , 
                      data = df_ana)
tab5_out <- createTable(tab5, digits.p = 2, digits = 2)
export2xls(tab5_out, "./outputs/sex-disaggregated-freq-sec-E.xlsx")
```

## Section F
```{r}
tab6 <- compareGroups(A2 ~ F1a + F1b + F1c + F1d + F1e + F1f + F1g + F1h + F1i + 
                        F1j + F2 + F3 + F4 + F5 + F6 + F7 + F8 + F9 + F10 + F11 + 
                        F12a + F12b + F12c + F12d + F12e + F12f + F12g + F12h + 
                        F12i + F12j + F12k + F12l + F12m + F12n + F13 , 
                      data = df_ana)
tab6_out <- createTable(tab6, digits.p = 2, digits = 2)
export2xls(tab6_out, "./outputs/sex-disaggregated-freq-sec-F.xlsx")
```

## Section G-1
```{r}
tab7 <- compareGroups(A2 ~ G1 + G2 + G3 + G4 + G5a + G5b + G5c + G5d + G5e + G5f + 
                        G5g + G5h + G5i + G5j + G5k + G5l + G6a + G6b + G6c + 
                        G6d + G6e + G6f + G6g + G6h + G6i + G6j + G6k + G6l + G7a_1 +  
                        G7a_2 + G7a_3 + G7a_4 + G7a_5 + G7b_1 + G7b_2 + G7b_3 + 
                        G7b_4 + G7b_5 + G7c_1 + G7c_2 +  G7c_3 + G7c_4 + G7c_5 + 
                        G7d_1 + G7d_2 + G7d_3 + G7d_4 + G7d_5 + G7e_1 + G7e_2 + 
                        G7e_3 + G7e_4 + G7e_5 + G7f_1 + G7f_2 + G7f_3 + G7f_4 + 
                        G7f_5 + G7g_1 + G7g_2 + G7g_3 + G7g_4 + G7g_5 + G7h_1 + 
                        G7h_2 + G7h_3 + G7h_4 + G7h_5 + G7i_1 + G7i_2 + G7i_3 + 
                        G7i_4 + G7i_5 + G7j_1 + G7j_2 + G7j_3 + G7j_4 + G7j_5 + 
                        G7k_1 + G7k_2 + G7k_3 + G7k_4 + G7k_5 + G7l_1 + G7l_2 + 
                        G7l_3 + G7l_4 + G7l_5 + G7Xa_1 + G7Xa_2 + G7Xa_3 + 
                        G7Xa_4 + G7Xa_5 + G7Xa_6 + G7Xb_1 + G7Xb_2 + G7Xb_3 + 
                        G7Xb_4 + G7Xb_5 + G7Xb_6 + G7Xc_1 + G7Xc_2 + G7Xc_3 + 
                        G7Xc_4 + G7Xc_5 + G7Xc_6 + G7Xd_1 + G7Xd_2 + G7Xd_3 + 
                        G7Xd_4 + G7Xd_5 + G7Xd_6 + G7Xe_1 + G7Xe_2 + G7Xe_3 + 
                        G7Xe_4 + G7Xe_5 + G7Xe_6 + G7Xf_1 + G7Xf_2 + G7Xf_3 + 
                        G7Xf_4 + G7Xf_5 + G7Xf_6 + G7Xg_1 + G7Xg_2 + G7Xg_3 + 
                        G7Xg_4 + G7Xg_5 + G7Xg_6 + G7Xh_1 + G7Xh_2 + G7Xh_3 + 
                        G7Xh_4 + G7Xh_5 + G7Xh_6 + G7Xi_1 + G7Xi_2 + G7Xi_3 + 
                        G7Xi_4 + G7Xi_5 + G7Xi_6 + G7Xj_1 + G7Xj_2 + G7Xj_3 + 
                        G7Xj_4 + G7Xj_5 + G7Xj_6 + G7Xk_1 + G7Xk_2 + G7Xk_3 + 
                        G7Xk_4 + G7Xk_5 + G7Xk_6 + G7Xl_1 + G7Xl_2 + G7Xl_3 + 
                        G7Xl_4 + G7Xl_5 + G7Xl_6 , 
                      data = df_ana)
tab7_out <- createTable(tab7, digits.p = 2, digits = 2)
export2xls(tab7_out, "./outputs/sex-disaggregated-freq-sec-G1.xlsx")
```

## Section G-2
```{r}
tab8 <- compareGroups(A2 ~ G8a + G8b + G8c + G8d + G8e + G8f + G8g + G8h + G8i + 
                        G8j + G8k + G8l + G9a + G9b + G9c + G9d + G9e + G9f + 
                        G9g + G9h + G9i + G9j + G9k + G9l + G10a_1 + G10a_2 + 
                        G10a_3 + G10a_4 + G10b_1 + G10b_2 + G10b_3 + G10b_4 + 
                        G10c_1 + G10c_2 + G10c_3 + G10c_4 + G10d_1 + G10d_2 + 
                        G10d_3 + G10d_4 + G10e_1 + G10e_2 + G10e_3 + G10e_4 + 
                        G10f_1 + G10f_2 + G10f_3 + G10f_4 + G10g_1 + G10g_2 + 
                        G10g_3 + G10g_4 + G10h_1 + G10h_2 + G10h_3 + G10h_4 + 
                        G10i_1 + G10i_2 + G10i_3 + G10i_4 + G10j_1 + G10j_2 + 
                        G10j_3 + G10j_4 + G10k_1 + G10k_2 + G10k_3 + G10k_4 + 
                        G10l_1 + G10l_2 + G10l_3 + G10l_4, 
                      data = df_ana)
tab8_out <- createTable(tab8, digits.p = 2, digits = 2)
export2xls(tab8_out, "./outputs/sex-disaggregated-freq-sec-G2.xlsx")
```

## Section G-3
```{r}
tab9 <- compareGroups(A2 ~ G10Xa_1 + G10Xa_2 + G10Xa_3 + G10Xa_4 + G10Xa_5 + 
                        G10Xb_1 + G10Xb_2 + G10Xb_3 + G10Xb_4 + G10Xb_5 + 
                        G10Xb_6 + G10Xc_1 + G10Xc_2 + G10Xc_3 + G10Xc_4 + 
                        G10Xc_5 + G10Xd_1 + G10Xd_2 + G10Xd_3 + G10Xd_4 + 
                        G10Xd_5 + G10Xe_1 + G10Xe_2 + G10Xe_3 + G10Xe_4 + 
                        G10Xe_5 + G10Xf_1 + G10Xf_2 + G10Xf_3 + G10Xf_4 + 
                        G10Xf_5 + G10Xg_1 + G10Xg_2 + G10Xg_3 + G10Xg_4 + 
                        G10Xg_5 + G10Xh_1 + G10Xh_2 + G10Xh_3 + G10Xh_4 + 
                        G10Xh_5 + G10Xi_1 + G10Xi_2 + G10Xi_3 + G10Xi_4 + 
                        G10Xi_5 + G10Xj_1 + G10Xj_2 + G10Xj_3 + G10Xj_4 + 
                        G10Xj_5 + G10Xk_1 + G10Xk_2 + G10Xk_3 + G10Xk_4 + 
                        G10Xk_5 + G10Xl_1 + G10Xl_2 + G10Xl_3 + G10Xl_4 + 
                        G10Xl_5 + G11 + G12 , 
                      data = df_ana)
tab9_out <- createTable(tab9, digits.p = 2, digits = 2)
export2xls(tab9_out, "./outputs/sex-disaggregated-freq-sec-G3.xlsx")
```

## Section H and I
```{r}
tab10 <- compareGroups(A2 ~ H1 + H2_1 + H2_2 + H2_3 + H2_4 + H2_5 + H2_6 + H3_1 + 
                        H3_2 + H3_3 + H3_4 + H3_5 + H4a + H4b + H4c + H4d + H4e + 
                        H4f + I1, 
                      data = df_ana)
tab10_out <- createTable(tab10, digits.p = 2, digits = 2)
export2xls(tab10_out, "./outputs/sex-disaggregated-freq-sec-H-I.xlsx")
```













