---
title: "function-for-three-way-weighted-table"
format: html
editor: visual
---

```{r}
text_matrix <- function(dat, table_title) {
  rbind(rep('', ncol(dat)),
        c(table_title, rep('', ncol(dat)-1)), # title
        rep('', ncol(dat)), # blank spacer row
        names(dat), # column names
        unname(sapply(dat, as.character))) # data

}
```

```{r}
df_col <- NULL
  # Start a loop for all survey objects by State
  for (svy in svy_obj_list) { 
  # Counter to reset the dataset for individual states
  df_rows <- NULL
    for (i in food_list) {
  # Create a single crosstab for  one variable by Sex
    a1 <- svytable(~get(i) + b4_01, design = svy) %>% 
    prop.table(2) %>% 
    magrittr::multiply_by(100) %>% 
    round(digits = 2) %>% 
    as.data.frame.array() %>% 
    mutate(Categories = rownames(.)) %>% 
    mutate("Male (N)" = with(svy$variables, table(get(i), b4_01))[,1]) %>% 
    mutate("Female (N)" = with(svy$variables, table(get(i), b4_01))[,2]) %>% 
    select(Categories, "Female (N)", "Female (%)" = female, "Male (N)", "Male (%)" = male) 
  
  # call the text matrix function to add a label for each variable  
  temp <- text_matrix(a1, label(df_Nigeria_IR_ana[[i]]))
  # Bind all variables within a section 
  df_rows <- rbind(df_rows, temp)
    }
  df_col <- cbind(df_col, df_rows)
  }
View(df_col)
# write.csv(df_col, file = "./outputs/food_lists.csv", row.names = F, col.names = F)
```